<?php

namespace AppBundle\Repository;

/**
 * CvAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
