<?php

namespace AppBundle\Repository;

/**
 * CvFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvFileRepository extends \Doctrine\ORM\EntityRepository
{
}
