<?php

namespace AppBundle\Repository;

/**
 * CvStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
