<?php

namespace AppBundle\Repository;

/**
 * CvViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvViewRepository extends \Doctrine\ORM\EntityRepository
{
}
