<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profile;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchProfiles($params)
    {
        $profileSearch = $this->createQueryBuilder('profile');

        if (empty($params['ignoreStatus']) || $params['ignoreStatus'] != true) {
            $profileSearch->where('profile.status = ' . Profile::ACTIVE_STATUS);
        }

        if (!empty($params['firstName'])) {
            $profileSearch->andWhere('profile.firstName like :name');
            $profileSearch->setParameter(':name', '%'.$params['firstName'].'%');
        }

        if (!empty($params['email'])) {
            $profileSearch->andWhere('profile.email like :email');
            $profileSearch->setParameter(':email', '%'.$params['email'].'%');
        }

        if (!empty($params['phone'])) {
            $profileSearch->andWhere('profile.phone like :phone');
            $profileSearch->setParameter(':phone', '%'.$params['phone'].'%');
        }

        $profiles = $profileSearch->getQuery()
            ->getResult();

        return $profiles;
    }
}
