<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cv;

/**
 * UserCvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCvRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get CV that belongs the given user
     * @param $userId
     * @param $cvId
     * @return Cv
     */
    public function getUserCv($userId, $cvId)
    {
        /** @var Cv[] $cvs */
        $cvs = $this->createQueryBuilder('cv')
            ->where('cv.userId = :userId')
            ->andWhere('cv.id = :id')
            ->andWhere('cv.status <> :status')
            ->setParameter('userId', $userId)
            ->setParameter('id', $cvId)
            ->setParameter('status', \AppBundle\Service\CvStatus::STATUS_BLOCKED)
            ->getQuery()
            ->getResult();

        if (empty($cvs)) {
            return [];
        }

        return $cvs[0];
    }

    /**
     * Search cv by parameters
     * @param $params
     */
    public function searchCV($params)
    {

        /** @var Cv[] $cvs */
        $cvSearch = $this->createQueryBuilder('cv');

        if (empty($params['ignoreStatus']) || $params['ignoreStatus'] != true) {
            $cvSearch->where('cv.status = ' . \AppBundle\Service\CvStatus::STATUS_PUBLISHED);
        }

        if (!empty($params['cvtitle'])) {
            $cvSearch->andWhere('cv.name like :title');
            $cvSearch->setParameter(':title', '%'.$params['cvtitle'].'%');
        }

        if (!empty($params['cvskill'])) {
            $cvSearch->andWhere('cv.skills like :skill');
            $cvSearch->setParameter(':skill', '%'.$params['cvskill'].'%');
        }

        if (!empty($params['industry'])) {
            $cvSearch->andWhere('cv.classifierId = :industry');
            $cvSearch->setParameter(':industry', $params['industry']);
        }

        if (!empty($params['region'])) {
            $cvSearch->andWhere('cv.region = :region');
            $cvSearch->setParameter(':region', $params['region']);
        }

        if (!empty($params['district'])) {
            $cvSearch->andWhere('cv.district = :district');
            $cvSearch->setParameter(':district', $params['district']);
        }

        $cvs = $cvSearch->getQuery()
            ->getResult();

        return $cvs;
    }


}
